### ISSUE TITLE
"Result: TypeError: Cannot read property 'length' of undefined" on running the import job on Parse

### ISSUE THREAD

**Issue by droidster** [FirebaseExtended/parse-migration-tools#6]
I'm getting this error when I run the import job:

```
Ran job import with:
  Input: {}
  Result: TypeError: Cannot read property 'length' of undefined
    at null.<anonymous> (migrator.js:270:42)
    at e (Parse.js:3:8736)
    at Parse.js:3:9489
    at g (Parse.js:3:9226)
    at c.extend.then (Parse.js:3:9474)
    at migrator.js:268:38
    at e (Parse.js:3:8736)
    at Parse.js:3:8185
    at Array.forEach (native)
    at Object.x.each.x.forEach [as _arrayEach] (Parse.js:1:661)
```

The object is undefined, could this be related to some config missing for Parse? Perhaps because of the ACL rules or something else is wrong at my end?

**Comment by inlined** [comment]
Hmm.. from a quick look it seems like https://github.com/firebase/parse-migration-tools/blob/master/cloud/migrator.js#L262 should have called the _.each and then just returned "changed". Does that quick change fix things for you?

**Comment by droidster** [comment]
I'm not sure what to change here. Can you give me some code?

**Comment by inlined** [comment]
I think (but don't have time to test yet since it's after 4AM local time) that line 262-265 of migrator.js should be changed from

``` js
        return _.each(changed, function(object) {
          object.set(consts.MIGRATION_KEY, consts.IMPORTED);
        });
```

to

``` js
        _.each(changed, function(object) {
          object.set(consts.MIGRATION_KEY, consts.IMPORTED);
        });
       return changed;
```

**Comment by droidster** [comment]
Still the same error. Yes, this can wait till tomorrow. :) 👍

**Comment by droidster** [comment]
Any updates on this?

**Comment by inlined** [comment]
Sorry, traveling + catching up on day job + food poisoning. 3bd4c4b changes the fetch and save commands to the new {useMasterKey: true} syntax that works in both Cloud Code and node code. Added a handful of tests as well. Hopefully this WFY. Will check out the next bug now.
